### PR TITLE
Update Relay to comply with wpilib changes. Fixes 253

### PR DESCRIPTION
**Pull request by Twinters007**

### CODE REVIEW

**Comment by virtuald** [comment]
Presumably this won't work without a corresponding HAL change?

**Comment by Twinters007** [comment]
No idea...I also didn't have to change any tests, so I may not understand the underlying issue very well.

**Comment by Twinters007** [comment]
Well, now that I look at the code, I can't tell what has changed between the two, except for the order of the if statements. The current code returns the same results it seems.

**Comment by virtuald** [comment]
If this is up to date, then can you validate it using git source-track too?

**Comment by Twinters007** [comment]
Yeah. Although I don't know how to write tests that test for...whatever was wrong? Maybe you can give some guidance to the problem and I can figure out a solution?

**Comment by auscompgeek** [comment]
I think #253 (and the corresponding upstream issue/PR) should explain it well enough…

**Comment by Twinters007** [comment]
Shouldn't need a HAL change. It's just the get() method that changed upstream as well.

**Comment by Twinters007** [comment]
Should I close this in favor of #304?

**Comment by auscompgeek** [comment]
Given that #304 has NT updates as well, I think that would make sense.

**Pull request closed without merging**
