### PR TITLE
Fix encoder fpga bug

### PR DESCRIPTION
**Pull request by Twinters007**

### CODE REVIEW

**Comment by Twinters007** [comment]
@auscompgeek if you merge this then @ariovistus 's test will pass and everything will be gucci

**Comment by auscompgeek** [comment]
uhm no what don't you want to return `encoderHandle.idx`?

**Comment by Twinters007** [comment]
I don't think the idx technically corresponds to the fpga index? It doesn't in the hal cpp implementation.

**Comment by Twinters007** [comment]
Nvm some deep searching proved that it does get changed to the idx and whatnot

**Pull request merged**
