### PR TITLE
update things that don't need to be updated for 2018

### PR DESCRIPTION
**Pull request by ariovistus**

### CODE REVIEW

**Comment by ariovistus** [comment]
hang on here, somebody updated upstream

**Comment by Twinters007** [comment]
Can you make a better commit message?

**Comment by ariovistus** [comment]
what are those stamps called? source-track stamps?

**Comment by Twinters007** [comment]
You could just say `verified non-changing files`

**Comment by virtuald** [comment]
One of your other PRs must have created a conflict.

**Pull request merged**
