### PR TITLE
Add the WPILib SerialPort object

### LINKED ISSUE #128: Need to port the SerialPort object
https://github.com/robotpy/allwpilib/blob/master/wpilibj/wpilibJavaDevices/src/main/java/edu/wpi/first/wpilibj/SerialPort.java

### PR DESCRIPTION
**Pull request by virtuald**
I don't have hardware to test this on. @dangyogi can you test this and see if it works for you?

* Fixes #128

### CODE REVIEW

**Comment by virtuald** [comment]
@DrWateryCat can you test this?

**Comment by DrWateryCat** [comment]
I can test tomorrow once I get access to the robot.

**Comment by DrWateryCat** [comment]
I'm trying to test right now, I can transmit strings fine. Recieving a string back from an arduino throws the following error:
```
Traceback (most recent call last): 
   File "/usr/local/lib/python3.6/site-packages/wpilib/robotbase.py", line 181, in main 
     robot.startCompetition() 
   File "/usr/local/lib/python3.6/site-packages/wpilib/iterativerobot.py", line 140, in startCompetition 
     self.teleopPeriodic() 
   File "/home/lvuser/py/robot.py", line 28, in teleopPeriodic 
     print(self.port.readString()) 
   File "/usr/local/lib/python3.6/site-packages/wpilib/serialport.py", line 179, in readString 
     return self.read(count).decode('ascii') 
   File "/usr/local/lib/python3.6/site-packages/wpilib/serialport.py", line 190, in read 
     return hal.readSerial(self.port, count) 
   File "/usr/local/lib/python3.6/site-packages/hal/functions.py", line 626, in readSerial 
     rv = _readSerial(port, buffer, count) 
   File "/usr/local/lib/python3.6/site-packages/hal/functions.py", line 38, in outer 
     rv = _inner(*args, status=status, **kwargs) 
 TypeError: c_char_p 'out' parameter must be passed as default value 
  
  
 Locals at innermost frame: 
  
 { '_inner': <CFunctionType object at 0xb65e40a0>, 
   'args': (2, <hal.functions.c_ubyte_Array_0 object at 0xb5a490d0>, 0), 
   'kwargs': {}, 
   'status': c_long(0)} 
```
With the python code: 
```python
self.port.writeString("test")
print(self.port.readString())
```

**Comment by virtuald** [comment]
I don't have time to edit this atm, but try removing `out=["buffer"]` from line 622 and see if that does it.

**Comment by DrWateryCat** [comment]
I'm out of time with the robot, expect more results on friday.

**Comment by virtuald** [comment]
Hey @DrWateryCat once again, haven't tested on a real rio, but I added some more tests and updated it a bit. Try it out and let me know if it works!

**Comment by virtuald** [comment]
@DrWateryCat did you ever get this to work?

**Pull request merged**
