### PR TITLE
Add python 3.7 to tests

### PR DESCRIPTION
**Pull request by virtuald**

### CODE REVIEW

**Comment by auscompgeek** [comment]
I wonder if we should start using Circle CI instead.

**Comment by auscompgeek** [comment]
Bleh. That didn't run 3.7. Let's try the other way of doing multiple jobs.

**Comment by auscompgeek** [comment]
Is declaring a build matrix and build stages mutually exclusive? Hmm...

**Comment by ariovistus** [comment]
not in my experience, e..g. https://github.com/ariovistus/pyd/blob/master/.travis.yml

**Comment by virtuald** [comment]
Looks like it ran in 3.7 this time?

**Comment by auscompgeek** [comment]
@ariovistus That doesn't look like it uses matrix.include.

**Pull request merged**
