### PR TITLE
Update motorsafety and add tests

### PR DESCRIPTION
**Pull request by twinters007**

### CODE REVIEW

**Comment by auscompgeek** [comment]
I don't see any tests failing without this alleged deadlock fix.

**Comment by Twinters007** [comment]
Well the timedrobot example wouldn't let me set a motor value without it

**Comment by auscompgeek** [comment]
You missed my point. Write a test for this.

**Comment by Twinters007** [comment]
Dumb me didn't realize that the lock was an instance variable

**Comment by auscompgeek** [comment]
Ok, this looks sane. Tests?

**Pull request merged**
