### PR TITLE
Update robotdrive for 2018

### PR DESCRIPTION
**Pull request by Twinters007**
I'm gonna be updating this as I go. Would you like 1 PR per file/group of files or just as many as I can do before you merge?

### CODE REVIEW

**Comment by virtuald** [comment]
1 PR per group doesn't seem unreasonable. Looks like the tests failed.

**Comment by Twinters007** [comment]
I don't see how the check failed 🤔

**Comment by Twinters007** [comment]
@virtuald ready for merge, then I have all the analog files validated

**Comment by virtuald** [comment]
This is why we have tests.

**Pull request merged**
