### PR TITLE
Change minimum required version to Python 3.6

### PR DESCRIPTION
**Pull request by M-Shadow**
Continuation of #612
Based on #606

### CODE REVIEW

**Comment by auscompgeek** [comment]
Might be worth taking the time to clean up this condition too whilst we're here.

**Comment by M-Shadow** [comment]
Pretty sure we can just use the `python_requires=">=3.6"` setup() arg and just remove the conditional.

**Comment by auscompgeek** [comment]
Yeah, I can't say I was ever really sure why we didn't just use `python_requires` here. We expect teams to install the pyfrc package on their computers after all, instead of installing wpilib directly.

On the other hand it does make some amount of sense for pyfrc to catch super-old versions of pip I guess.

**Comment by virtuald** [comment]
I believe when I first created these things, I didn't realize that python_requires existed or (more likely) it didn't exist at the time.

**Comment by auscompgeek** [comment]
python_requires is pretty old now; iirc it definitely existed at the time.

**Pull request merged**
