### PR TITLE
Use "append" for NetworkTable Arrays

### PR DESCRIPTION
**Pull request by FRC2539**
StringArray and NumberArray objects do not have an "add" method, but they do have "append" which appears to have the desired behavior.

### CODE REVIEW

**Comment by virtuald** [comment]
If you're exploring the command framework, take note of https://github.com/robotpy/robotpy-wpilib/issues/195

**Comment by FRC2539** [comment]
We have taken note of it. Say a team was looking to use the command-based paradigm in what they feel is a pythonic manner in order to maintain consistency with the other languages (and hopefully therefore be able to help and get help from teams that use other languages at competitions). What would they need to do in order to avoid it being deprecated?

**Comment by james-ward** [comment]
As someone who spent a bit of time working on the command based examples and getting command based stuff to work better with the simulator at the end of last year, I feel qualified to say "don't do command based!"
We started using it this year, and as soon as Dustin released his MagicBot framework we switched over. Even refactoring in the middle of the build season was worth it. It is so much easier and cleaner to work with.
I would prioritise ease of use, lack (less?? :-P ) weird edge cases, and speed of design iteration above "compatibility" with other languages. Using Python is gaining traction, but you are still likely to come across FTAs that won't help when they find you are using Python (they might even tell you that using Python on the bot is not legal... fun times...), so consistency with other languages is unlikely to get you much there anyway. [For the sake of those reading this post in the future, using Python on your robot at a competition absolutely is legal (and highly recommended!)]

**Comment by virtuald** [comment]
If you have a good rationale for keeping it, then a comment on #195 would be appropriate. Given that the goal of robotpy's WPILib port is to make everything available in Java available in Python also, it won't go away for the moment -- but if we add the warnings then you'll just get annoying warnings if you use it, and I'm not going to put much effort into improving it beyond what Java provides.

Fundamentally, I dislike Command-based programming because it requires too much boilerplate. It takes a large amount of text to do simple things -- after all, this is one of the reasons why RobotBuilder exists. It has a very 'Java' feel to it, and I don't think you can change it to be pythonic without significant changes.

One last complaint is that Python code tends to crash very easily as compared to Java (for example, accessing an attribute that doesn't exist, which would get caught by the Java compiler). The command framework doesn't currently have a good way to deal with these sorts of things, as Java doesn't have this problem. There are probably ways of dealing with this, but I haven't dug into it very much.

**Pull request merged**
