### PR TITLE
Disarm GIL threadstate deletion if interpreter is exiting

### PR DESCRIPTION
**Pull request by virtuald**

### CODE REVIEW

**Comment by virtuald** [comment]
I'm not really sure this is the right fix, but it'll do for now.

**Comment by virtuald** [comment]
This did not actually solve the problem, something else is happening.

**Comment by auscompgeek** [comment]
Maybe SafeThread is blowing up?

**Comment by virtuald** [comment]
Yes, that was also an issue. I forgot to push a fix for that last night.

**Pull request merged**
